/**
 * CasyEmergencyHelp - the nearest SPECIFIC places to get help right now,
 * generated by Casy for the person's location AND their exact situation from
 * the triage (e.g. dental pain + no insurance -> a free dental clinic, not the
 * ER). Regenerates whenever the situation changes so it's always sensitive to
 * what the person just answered.
 */
import React, { useEffect, useRef, useState } from 'react';
import { View, Text, StyleSheet, ActivityIndicator, TouchableOpacity } from 'react-native';
import { useApp } from '../context/AppContext';
import { generateEmergencyHelp, buildAnswersSummary, UserContext } from '../services/aiService';
import { PlanRecommendation } from '../types';
import { CasyResources } from './CasyResources';
import { CasyAvatar } from './CasyAvatar';

interface Props {
  kind: 'healthcare' | 'housing';
  isSpanish: boolean;
  // A short description of what the person just told the triage (their exact
  // situation), so Casy routes them to the right place.
  situation?: string;
}

export const CasyEmergencyHelp: React.FC<Props> = ({ kind, isSpanish, situation }) => {
  const { state } = useApp();
  const profile = state.userProfile;

  const [items, setItems] = useState<PlanRecommendation[] | null>(null);
  const [loading, setLoading] = useState(false);
  const [failed, setFailed] = useState(false);
  const lastKeyRef = useRef<string | null>(null);

  const buildContext = (): UserContext => ({
    name: profile?.name,
    city: profile?.location?.city,
    state: profile?.location?.state,
    language: isSpanish ? 'es' : 'en',
    needs: profile?.selectedCategories,
    ageGroup: profile?.ageGroup,
    isMinor: profile?.ageGroup === 'under18',
    answersSummary: buildAnswersSummary(profile?.answers, isSpanish ? 'es' : 'en'),
  });

  const fetchHelp = async () => {
    setLoading(true);
    setFailed(false);
    try {
      const res = await generateEmergencyHelp(buildContext(), kind, situation);
      if (res && res.length) setItems(res);
      else setFailed(true);
    } catch {
      setFailed(true);
    } finally {
      setLoading(false);
    }
  };

  // Regenerate whenever the situation (triage answers) changes.
  useEffect(() => {
    const key = `${kind}|${situation || ''}`;
    if (lastKeyRef.current !== key) {
      lastKeyRef.current = key;
      fetchHelp();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [kind, situation]);

  const heading = isSpanish ? 'PARA TU SITUACIÓN, AHORA' : 'FOR YOUR SITUATION, RIGHT NOW';

  if (loading && !items) {
    return (
      <View style={styles.wrap}>
        <CasyAvatar size={26} />
        <ActivityIndicator color="#DC2626" style={{ marginVertical: 8 }} />
        <Text style={styles.text}>
          {isSpanish
            ? 'Casy está buscando el lugar correcto para ti...'
            : 'Casy is finding the right place for you...'}
        </Text>
      </View>
    );
  }

  if (failed && !items) {
    return (
      <View style={styles.wrap}>
        <Text style={styles.text}>
          {isSpanish
            ? 'No pude cargar lugares cercanos ahora.'
            : "Couldn't load nearby places right now."}
        </Text>
        <TouchableOpacity style={styles.retryBtn} onPress={fetchHelp}>
          <Text style={styles.retryText}>{isSpanish ? 'Reintentar' : 'Try again'}</Text>
        </TouchableOpacity>
      </View>
    );
  }

  if (!items || items.length === 0) return null;

  return (
    <View style={styles.container}>
      <CasyResources resources={items} isSpanish={isSpanish} label={heading} />
      <TouchableOpacity style={styles.refreshBtn} onPress={fetchHelp} disabled={loading}>
        {loading ? (
          <ActivityIndicator color="#DC2626" size="small" />
        ) : (
          <Text style={styles.refreshText}>{isSpanish ? '↻ Actualizar' : '↻ Refresh'}</Text>
        )}
      </TouchableOpacity>
    </View>
  );
};

const styles = StyleSheet.create({
  container: { marginBottom: 8 },
  wrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 22,
    backgroundColor: '#FEF2F2',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#FECACA',
    marginBottom: 16,
  },
  text: {
    fontSize: 13.5,
    color: '#B91C1C',
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 4,
    paddingHorizontal: 16,
  },
  retryBtn: {
    marginTop: 12,
    paddingHorizontal: 18,
    paddingVertical: 9,
    backgroundColor: '#DC2626',
    borderRadius: 999,
  },
  retryText: { color: '#fff', fontWeight: '800', fontSize: 13 },
  refreshBtn: { alignSelf: 'flex-start', marginTop: -6, marginBottom: 12, padding: 4 },
  refreshText: { color: '#DC2626', fontWeight: '800', fontSize: 13 },
});
