/**
 * CasyEmergencyHelp - the nearest SPECIFIC places to get help right now,
 * generated by Casy for the person's location (closest ER / urgent care /
 * free clinic, or emergency shelter / drop-in). Shown on the "Need Help Now"
 * screens so they name real local options instead of only 211/911.
 * Cached in the profile under "<kind>_urgent" so it's instant next time.
 */
import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, ActivityIndicator, TouchableOpacity } from 'react-native';
import { useApp } from '../context/AppContext';
import { generateEmergencyHelp, buildAnswersSummary, UserContext } from '../services/aiService';
import { CasyResources } from './CasyResources';
import { CasyAvatar } from './CasyAvatar';

interface Props {
  kind: 'healthcare' | 'housing';
  isSpanish: boolean;
}

export const CasyEmergencyHelp: React.FC<Props> = ({ kind, isSpanish }) => {
  const { state, dispatch } = useApp();
  const profile = state.userProfile;
  const storeKey = `${kind}_urgent`;
  const saved = profile?.categoryPicks?.[storeKey];

  const [loading, setLoading] = useState(false);
  const [failed, setFailed] = useState(false);

  const buildContext = (): UserContext => ({
    name: profile?.name,
    city: profile?.location?.city,
    state: profile?.location?.state,
    language: isSpanish ? 'es' : 'en',
    needs: profile?.selectedCategories,
    ageGroup: profile?.ageGroup,
    isMinor: profile?.ageGroup === 'under18',
    answersSummary: buildAnswersSummary(profile?.answers, isSpanish ? 'es' : 'en'),
  });

  const fetchHelp = async () => {
    setLoading(true);
    setFailed(false);
    try {
      const items = await generateEmergencyHelp(buildContext(), kind);
      if (items && items.length) {
        dispatch({ type: 'SET_CATEGORY_PICKS', payload: { category: storeKey, items } });
      } else {
        setFailed(true);
      }
    } catch {
      setFailed(true);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!saved && !loading && !failed) fetchHelp();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const heading = isSpanish ? 'AYUDA MÁS CERCANA AHORA' : 'NEAREST HELP RIGHT NOW';

  if (loading && !saved) {
    return (
      <View style={styles.wrap}>
        <CasyAvatar size={24} />
        <ActivityIndicator color="#DC2626" style={{ marginVertical: 8 }} />
        <Text style={styles.text}>
          {isSpanish
            ? 'Casy está buscando ayuda cerca de ti...'
            : 'Casy is finding help near you...'}
        </Text>
      </View>
    );
  }

  if (failed && !saved) {
    return (
      <View style={styles.wrap}>
        <Text style={styles.text}>
          {isSpanish
            ? 'No pude cargar lugares cercanos ahora.'
            : "Couldn't load nearby places right now."}
        </Text>
        <TouchableOpacity style={styles.retryBtn} onPress={fetchHelp}>
          <Text style={styles.retryText}>{isSpanish ? 'Reintentar' : 'Try again'}</Text>
        </TouchableOpacity>
      </View>
    );
  }

  if (!saved || saved.length === 0) return null;

  return (
    <View style={styles.container}>
      <CasyResources resources={saved} isSpanish={isSpanish} label={heading} />
      <TouchableOpacity style={styles.refreshBtn} onPress={fetchHelp} disabled={loading}>
        {loading ? (
          <ActivityIndicator color="#DC2626" size="small" />
        ) : (
          <Text style={styles.refreshText}>
            {isSpanish ? '↻ Actualizar' : '↻ Refresh'}
          </Text>
        )}
      </TouchableOpacity>
    </View>
  );
};

const styles = StyleSheet.create({
  container: { marginBottom: 8 },
  wrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    backgroundColor: '#FEF2F2',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#FECACA',
    marginBottom: 16,
  },
  text: {
    fontSize: 13.5,
    color: '#B91C1C',
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 4,
  },
  retryBtn: {
    marginTop: 12,
    paddingHorizontal: 18,
    paddingVertical: 9,
    backgroundColor: '#DC2626',
    borderRadius: 999,
  },
  retryText: { color: '#fff', fontWeight: '800', fontSize: 13 },
  refreshBtn: { alignSelf: 'flex-start', marginTop: -6, marginBottom: 12, padding: 4 },
  refreshText: { color: '#DC2626', fontWeight: '800', fontSize: 13 },
});
